# Generated by Django 4.1.5 on 2023-01-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_complete_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='details',
            field=models.CharField(default='abc', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='abc', max_length=100),
        ),
    ]
